- name: Secopx Sensor - Automated installation
  hosts: all
  remote_user: root
  sudo: no
  tasks:
        
    - name: instal prerequisits
      ansible.builtin.package:
          name: 
              - wget
              - zip
          state: latest

    - name: Download zip file from secopx.com
      command: chdir=/root/ wget https://secopx.com/secopx-sensor.zip
            
    - name: Extract zip
      command: chdir=/root/ wget unzip secopx-sensor.zip

    - name: Include uuid list
      include_vars: uuid_list.yml

    - name: Create license files and take a uuid from list
      copy:
          dest: "/root/IntruSense-v30/License_{{ play_hosts.index(inventory_hostname) }}.txt"
          content: |
                "# Secopx.com User License"
                "# ======================="
                "# This file should be placed at the sensor's working folder."
                "Key: {{ uuid[play_hosts.index(inventory_hostname)] | from_yaml  }}"
                "Password: {{ tmp_pwd | from_yaml }}"
                "Name: {{ username | from_yaml }}"

    - name: Include configurations file 
      include_vars: config.yml

    - name: Create config file
      copy:
          dest: "/root/IntruSense-v30/secopx.conf"
          content: |
                'WEBSERVER_DIR="{{ WEBSERVER_DIR | from_yaml }}"'
                'SYSLOG_FILE="{{ SYSLOG_FILE  | from_yaml }}"'
                'ERROR_LOG_FILE="{{ ERROR_LOG_FILE  | from_yaml }}"'
                'ACCESS_LOG_FILE="{{ ACCESS_LOG_FILE | from_yaml }}"'
                'LOG_MESSAGES="{{ LOG_MESSAGES | from_yaml }}"'
                'MAIL_LOG_FILE="{{ MAIL_LOG_FILE  | from_yaml }}"'
                'CONTAINER_ENV="{{ CONTAINER_ENV | from_yaml }}"'
                'VOLUMES_DIR="{{ VOLUMES_DIR | from_yaml }}"'
                'REGISTRY_VOL="{{ REGISTRY_VOL | from_yaml }}"'
                'CUSTOM_LOG="{{ CUSTOM_LOG | from_yaml }}"'
                'QUARANTINE_CRYPTO="{{ QUARANTINE_CRYPTO | from_yaml }}"'
                'REPORT_MODE="{{ REPORT_MODE | from_yaml }}"'
                'YARA_SIZE_LIMIT="{{ YARA_SIZE_LIMIT | from_yaml }}"'
                'DEEP_SCAN_MODE="{{ DEEP_SCAN_MODE | from_yaml }}"'

    - name: Run convenient installation script
      command: chdir=/root/IntruSense-v30/convenient-installation-script.bash
